apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudmart-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::039612844200:role/cloudmart-fastapi-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmart
  template:
    metadata:
      labels:
        app: cloudmart
    spec:
      serviceAccountName: cloudmart-app
      containers:
      - name: cloudmart
        image: 039612844200.dkr.ecr.us-east-1.amazonaws.com/cloudmart:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: ADMIN_USERNAME
          value: "admin"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudmart-secrets
              key: admin-password
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudmart-secrets
              key: openai-api-key
        - name: OPENAI_ASSISTANT_ID
          valueFrom:
            secretKeyRef:
              name: cloudmart-secrets
              key: openai-assistant-id
        - name: BEDROCK_AGENT_ID
          valueFrom:
            secretKeyRef:
              name: cloudmart-secrets
              key: bedrock-agent-id
        - name: BEDROCK_AGENT_ALIAS_ID
          valueFrom:
            secretKeyRef:
              name: cloudmart-secrets
              key: bedrock-agent-alias-id
        - name: AZURE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: cloudmart-secrets
              key: azure-endpoint
        - name: AZURE_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudmart-secrets
              key: azure-api-key
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudmart
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: cloudmart 