apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudmart-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/cloudmart-fastapi-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmart-backend
  template:
    metadata:
      labels:
        app: cloudmart-backend
    spec:
      serviceAccountName: cloudmart-app
      containers:
      - name: cloudmart-backend
        image: ${ECR_REGISTRY}/cloudmart-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: ADMIN_USERNAME
          value: "admin"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudmart-secrets
              key: admin-password
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudmart-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: cloudmart-backend 